### PR TITLE
taskmasterctl basic functionality

### LINKED ISSUE #3: Implement Taskmasterctl CLI inputs
Program should be able to expect any input without any unexpected behavior and implement the following flags:

- [x] help
- [x] version
- [x] #8
- [ ] ???

### PR DESCRIPTION
**Pull request by Ragarnoy**
closes #3

### CODE REVIEW

File: taskmasterctl/src/main.rs [hunk 1]
```diff
@@ -69,6 +102,6 @@ fn read_from_stream(unix_stream: &mut UnixStream) -> Result<()> {
     unix_stream
         .read_to_string(&mut response)
         .context("Failed at reading from the unix stream")?;
-    println!("response: {}", response);
+    println!("response: \n{}", response);
```
Comment (Eviber) [inline taskmasterctl/src/main.rs]:
```suggestion
    println!("response:\n{}", response);
```

**Review by Eviber — APPROVED** [review]
